D8 port
pfrenssen/filecache pull request #1
Opened 2018-09-04 13:57 UTC by pfrenssen

2018-09-19 13:42 UTC, claudiu-cristea requested changes
I like very much the work that has been done here. Everything looks very clean, we have tests, coding standards. Everything. However, there are some remarks inline with the code. Apart from that, when this is merged, the project description should be updated accordingly, at https://www.drupal.org/project/filecache

2018-09-19 13:42 UTC, claudiu-cristea commented on composer.json
> +        "drupal/core": "~8.5"
At the time this will be merged, the current Drupal stable release is based on `8.6.x` branch. However, recently - at Drupal Europe, Dries announced that [Drupal minor releases will benefit of extended security coverage for 6 months after the next minore stable is released](https://dri.es/extended-security-coverage-for-drupal-8-minor-releases). Meaning that `8.5.x` will still receive security updated till the end of March 2019. But keep in mind that `8.5.x` is supported only as security, so for me it's OK to require any of `8.5.x` or `8.6.x`. I'll let you decide, as a module co-maintainer.

2018-09-19 13:42 UTC, claudiu-cristea commented on composer.json
> +    "require-dev": {
Shouldn't we requires `drupal/core:8.7.x`, which is the current development branch, for testing?

2018-09-19 13:42 UTC, claudiu-cristea commented on src/Cache/FilesystemBackendFactory.php
> +      $path = $path_settings['bins'][$bin];
Let's not trust what the site builder has added in `settings.php` and do a `rtrim(...., '/')` also here. I see we are doing the same with `$settings['filecache_directory']['default']`.

EDIT: Oh, I see we're doing it in `FilesystemBackend::__construct()`, but as this protected method is suppose to return the bin path, let's return an already cleaned path.

2018-09-19 13:42 UTC, claudiu-cristea commented on src/Cache/FilesystemBackendFactory.php
> +    return new FilesystemBackend($this->filesystem, $this->time, $this->checksumProvider, $path);
I see that core backends are doing the same, they are hardcoding the backend class, so it's not possible to reuse this factory with different class, for example if a 3rd party module wants to extend `FilesystemBackend` but still use this factory. It's only an observation, no change is required.

2018-09-19 13:42 UTC, claudiu-cristea commented on src/Cache/FilesystemBackend.php
> +   *   The path or streamwrapper URI of the file to load.
streamwrapper > stream wrapper

2018-09-19 13:42 UTC, claudiu-cristea commented on src/Cache/FilesystemBackend.php
> +    assert(Inspector::assertAllStrings($tags, 'Cache Tags must be strings.'));
The description is parameter of `assert()`, not of `Inspector::assertAllStrings()`.

2018-09-19 13:42 UTC, claudiu-cristea commented on src/Cache/FilesystemBackend.php
> +   * @param \stdClass $item
s/\stdClass/object - according to https://www.drupal.org/docs/develop/standards/api-documentation-and-comment-standards#types

2018-09-19 13:42 UTC, claudiu-cristea commented on src/Cache/FilesystemBackend.php
> +  protected function getRequestTime() {
Hm... Superfluity. Using directly `$this->time->getRequestTime()` looks straight for me but it's a matter of taste, of course. Keep it.

2018-09-19 13:42 UTC, claudiu-cristea commented on src/Cache/FilesystemBackend.php
> +   * @return \stdClass|null
s/\stdClass/object - according to https://www.drupal.org/docs/develop/standards/api-documentation-and-comment-standards#types

2018-09-19 13:42 UTC, claudiu-cristea commented on src/Cache/FilesystemBackend.php
> +      // We are dealing with a flat list of files. If there are any folders
> We are dealing with a flat list of files

Yeah, but this could be a performance issue on some file systems (most of them on Linux), when the number of directory entries are exceeding a limit. And we cache because we want more speed, this is the reason of a cache system. Performance is really an issue here. But as this is the first try on Drupal 8.x let's create a follow-up that would reorganize the backend in a structured way, so that we'll have a sane files count in a directory. Please, link here with a TODO.

2018-09-19 13:42 UTC, claudiu-cristea commented on src/Cache/FilesystemBackend.php
> +      if (!mkdir($this->path, 0755, TRUE)) {
Is there a good reason for not using `$this->filesystem->mkdir()`?

2018-09-19 13:42 UTC, claudiu-cristea commented on filecache.services.yml
> +    class: Drupal\filecache\Cache\FilesystemBackendFactory
A general remark on spelling the term _file system_. The core is using the camelized name: `FileSystem`. That said, it looks like the correct name is "file system" (2 words), not "filesystem". Wikipedia spells the term also as 2 word: https://en.wikipedia.org/wiki/File_system. And there are a plethora of debates where, in the most of the cases, the "2 word" form is the winner. My spell checker also complains :) I know, we cannot change the module name but, at least, we can do it in the class names and identifiers (such as `cache.backend.filesystem` > `cache.backend.file_system`).

2018-09-19 13:42 UTC, claudiu-cristea commented on src/Cache/FilesystemBackend.php
> +   *   An cache ID consisting of alphanumeric characters, hypens and underscores
s/hypens/hyphens

2018-09-19 13:42 UTC, claudiu-cristea commented on tests/src/Kernel/FilesystemBackendTest.php
> +  protected function tearDown() {
Isn't it possible to implement `GenericCacheBackendUnitTestBase::tearDownCacheBackend()` here. I haven't researched.

2018-09-19 13:42 UTC, claudiu-cristea commented on .travis.yml
> +    - TEST_SUITE=8.6.x
As I commented in `composer.json`, I think we should run tests with `8.7.x`.

2018-09-19 13:42 UTC, claudiu-cristea commented on .travis.yml
> +  - composer install
Are we installing the whole codebase for `PHP_CodeSniffer`? We need only PHPCS & Coder.

2018-09-19 13:42 UTC, claudiu-cristea commented on scripts/travis-ci/run-test.sh
> +mysql_to_ramdisk() {
Wow, amazing!

2018-09-19 13:42 UTC, claudiu-cristea commented on filecache.install
> +  $bins = Cache::getBins();
This value is never used.

2018-09-19 22:49 UTC, pfrenssen commented on src/Cache/FilesystemBackendFactory.php
> +      $path = $path_settings['bins'][$bin];
Good point, thanks, I will make sure this indeed already returns a cleaned path.

2018-09-19 22:54 UTC, pfrenssen commented on composer.json
> +        "drupal/core": "~8.5"
It's the minimum required version for the code to work. I think this is not connected to whether or not the version is still supported but rather the minimum API version. To be honest it might also work with lower versions, but I didn't test these so I am not comfortable declaring a lower version.

I'll keep it on `~8.5` for now.

2018-09-19 22:58 UTC, pfrenssen commented on composer.json
> +    "require-dev": {
Hmm I don't think so, since 8.7.x is not _required_ for doing development on the module. You can have Drupal 8.5 installed and develop new features without problems. I do agree we should run the tests on 8.7.x now.

2018-09-19 22:59 UTC, pfrenssen commented on src/Cache/FilesystemBackend.php
> +   * @return \stdClass|null
Oh good point, I should know this :sweat_smile:

2018-09-19 23:00 UTC, pfrenssen commented on .travis.yml
> +  - composer install
Yeah, there is no way around that, Coder depends on PHP_CodeSniffer.

2018-09-19 23:01 UTC, pfrenssen commented on scripts/travis-ci/run-test.sh
> +mysql_to_ramdisk() {
Thanks, I stole it from OG :grin:

2018-09-20 19:02 UTC, pfrenssen commented on src/Cache/FilesystemBackend.php
> +  protected function getRequestTime() {
Hmm yeah, this is a remnant from an earlier iteration where this was written using PHP 7.1 return types. I remember adding this so I could document that this is an integer. I will keep it for now, in a few months PHP 5.6 and 7.0 are EOL and we can start porting this back to PHP 7.1

2018-09-20 19:08 UTC, pfrenssen commented on src/Cache/FilesystemBackend.php
> +      // We are dealing with a flat list of files. If there are any folders
Yes I agree. A common technique is to create subfolders for the first character in the filename. I will make an issue for this and link it.

2018-09-20 19:35 UTC, claudiu-cristea commented on src/Cache/FilesystemBackend.php
> +      // We are dealing with a flat list of files. If there are any folders
The filename is more likely to be the cid. If a site is extensively caching something like `item:{item_id}` in an arbitrary bin, then it might create a directory with a huge number of entries in `FilesystemBackendFactory:: getPathForBin('arbitrary_bin') . '/i'`. So, probably, it would be a good idea to consider a more random value.

2018-09-20 19:38 UTC, pfrenssen commented on tests/src/Kernel/FilesystemBackendTest.php
> +  protected function tearDown() {
I tried this but no it doesn't work, this method is called too late. We are trying to avoid the calls to `CacheBackendInterface::deleteAll()`, and the the `tearDownCacheBackend()` is called after that.

2018-09-20 19:41 UTC, pfrenssen commented on .travis.yml
> +  - composer install
Ah I misunderstood. Yes we are installing all dependencies, even Drupal core etc for the coding standards check. This takes some time, but the tests run in parallel and this is in fact the fastest test so we won't gain a lot. I would accept pull requests for this though :)

2018-09-20 20:00 UTC, pfrenssen commented on src/Cache/FilesystemBackend.php
> +      // We are dealing with a flat list of files. If there are any folders
https://www.drupal.org/project/filecache/issues/3001324

2018-09-20 20:02 UTC, pfrenssen commented on filecache.services.yml
> +    class: Drupal\filecache\Cache\FilesystemBackendFactory
OK you're right. I will rename all the things :smile:

2018-09-21 09:32 UTC, pfrenssen commented
This is currently failing because of https://github.com/pfrenssen/coder/issues/14

2018-09-27 08:02 UTC, claudiu-cristea commented on src/Cache/FilesystemBackend.php
> +      if (!mkdir($this->path, 0755, TRUE)) {
This was not addressed.

2018-09-27 08:40 UTC, claudiu-cristea approved these changes

2018-09-27 08:40 UTC, merged